version: '3.7'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094" # New port mapping for external connections
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "stock-data:1:1"
    depends_on:
      - zookeeper

  producer:
    build: .
    container_name: producer
    volumes:
      - .:/app
    command: ./wait-for-it.sh kafka:9092 -- python producer.py
    depends_on:
      - kafka

  consumer:
    build: .
    container_name: consumer
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ./wait-for-it.sh kafka:9092 -- python backend.py
    depends_on:
      - kafka
