SYMBOLS = [{"symbol":"DXYN","description":"The Dixie Group, Inc."},
{"symbol":"DYN.WS","description":"Dynegy Inc."},
{"symbol":"IRM","description":"Iron Mountain Incorporated"},
{"symbol":"JRVR","description":"James River Group Holdings, Ltd."},
{"symbol":"CALI","description":"China Auto Logistics Inc."},
{"symbol":"LUX","description":"Luxottica Group, S.p.A."},
{"symbol":"BHE","description":"Benchmark Electronics, Inc."},
{"symbol":"RLI","description":"RLI Corp."},
{"symbol":"NVS","description":"Novartis AG"},
{"symbol":"ICBK","description":"County Bancorp, Inc."},
{"symbol":"WIT","description":"Wipro Limited"},
{"symbol":"FNB^E","description":"F.N.B. Corporation"},
{"symbol":"EVT","description":"Eaton Vance Tax Advantaged Dividend Income Fund"},
{"symbol":"VALE","description":"VALE S.A."},
{"symbol":"TS","description":"Tenaris S.A."},
{"symbol":"HTH","description":"Hilltop Holdings Inc."},
{"symbol":"RE","description":"Everest Re Group, Ltd."},
{"symbol":"CBX","description":"CBX (Listing Market NYSE Networks AE"},
{"symbol":"SRNE","description":"Sorrento Therapeutics, Inc."},
{"symbol":"CGEN","description":"Compugen Ltd."}] # Produced with https://www.mockaroo.com/